### ISSUE TITLE
如果是自定义components应该如何引用mitoo的组件？

### ISSUE THREAD

**Issue by hopkinson** [Mitoo-FE/Mitoo-weapp-mpvue#1]
在
![image](https://user-images.githubusercontent.com/13248613/42766346-d2a1cc86-894c-11e8-97a8-8276e1a94ad2.png)
`src/components`文件夹下应该怎么引入这些组件，可以指引下？

**Comment by angel8731** [comment]
你好，用法和在page中的用法是一样的，需要在你的json文件中引入组件的引用。
列如下边这样：
`{
	"component": true,
	"usingComponents": {
		"mit-icon": "/components/Icon/index"
	}
}`
目录是绝对路径，我们是从npm包中copy过来的，所以也不需要变，直接用就好
